amine_homepage:
    path:     /
    defaults: { _controller: AmineBundle:Default:index }
amine_contact:
    path: /nous-contacter
    defaults: { _controller: AmineBundle:Default:contact }	
amine_page:
    path: /page/{slug}
    defaults: { _controller: AmineBundle:Default:page}
