imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info
        main_critical:
            type: fingers_crossed
            action_level: critical
            handler: grouped
        grouped:
            type: group
            members: [streamed, buffered] 
        streamed:
            type: rotating_file
            max_files: 15
            path: %kernel.logs_dir%/%kernel.environment%.critical.log
            level: info     
        buffered:
            type: buffer
            handler: swift
        swift:
            type: swift_mailer
            from_email: 'amine.betari@gmail.com'
            to_email: 'amine1.betari@gmail.com'
            subject: Critical Error Ocuured
            level: error

#swiftmailer:
#    delivery_address: me@example.com
