amine:
    resource: "@AmineBundle/Resources/config/routing.yml"
    # prefix:   /{_locale}

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type: annotation
    prefix: /admin

# hwi_oauth_redirect:
    # resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    # prefix:   /connect
 
# hwi_oauth_login:
    # resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    # prefix:   /login	
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}/

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/platform

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

#sg_datatables_bundle:
#    resource: "@SgDatatablesBundle/Controller/"
#    type:     annotation	

#login: 
#    path: /login
#    defaults:
#        _controller: OCUserBundle:Security:login		
#login_check:
#    path: /login_check	
#logout:
#    path: /logout
