oc_platform_delete_element:
    path: /advert/delete
    defaults:
        _controller: OCPlatformBundle:Advert:deleteRelation
    condition: "request.isXmlHttpRequest()"        
oc_platform_view:
    path:    /advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+
oc_platform_view_skill:
    path:    /skill/{id}
    defaults:
        _controller: OCPlatformBundle:Skill:view
    requirements:
        id: \d+
oc_platform_category:
    path: /category/{name}		
    defaults: 
        _controller: OCPlatformBundle:Advert:listadvertbycategory
oc_platform_delete_application:
    path: /delete-application/{id}		
    defaults:
        _controller: OCPlatformBundle:Advert:deleteapplication
    requirements :
        id: \d+
oc_platform_purge:
    path: /purge/{days}
    defaults:
        _controller: OCPlatformBundle:Advert:purge
    requirements:
        days: \d+
oc_platform_test:
    path: /test/{id}
    defaults: { _controller : OCPlatformBundle:Advert:test } 	
    requirements:
        id: \d+
oc_platform_home:
    path: /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*
oc_platform_list_skill:
    path: /skill/{page}
    defaults:
        _controller: OCPlatformBundle:Skill:index
        page: 1
    requirements:
        page: \d*
oc_platform_add:
    path: /add
    defaults:
        _controller: OCPlatformBundle:Advert:add
oc_platform_add_skill:
    path: /add/skill
    defaults:
        _controller: OCPlatformBundle:Skill:add
oc_platform_edit:
    path: /edit/{id}
    defaults: { _controller : OCPlatformBundle:Advert:edit }
    requirements : { id: \d+ }
oc_platform_edit_skill:
    path: /edit/skill/{id}
    defaults: { _controller : OCPlatformBundle:Skill:edit }
    requirements : { id: \d+ }
oc_platform_delete:
    path: /delete/{id}    
    defaults : 
        _controller : OCPlatformBundle:Advert:delete
    requirements :
        id: \d+
oc_platform_view_slug:
    path:    /{year}/{slug}.{_format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        _format:    html
    requirements:
        year: \d{4}
        _format: html|xml|json
