services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50
    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            -  "@mailer"
    oc_platfrom_doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
#        tags: [name: doctrine.event_listner, event: postPersist]
    oc_platform.purger.advert:
        class: OC\PlatformBundle\Purge\AdvertArchive
        arguments:
            - "@doctrine.orm.default_entity_manager"