<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
	
	/**
	* Liste des annonces sans candidature
	* @param $days : int
	*/
	public function getAdvertsWithoutCandidatureBeforeDays($days)
	{
		$queryBuilder = $this->createQueryBuilder('a');
		//$queryBuilder = $queryBuilder->leftjoin('a.applications','app')->addSelect('app');
		
		$queryBuilder = $queryBuilder->where('a.updatedAt <= :days');
		$queryBuilder = $queryBuilder->orWhere('a.updatedAt IS NULL AND a.date <= :days');
		$queryBuilder = $queryBuilder->andwhere('a.applications IS EMPTY');
		//$queryBuilder = $queryBuilder->setParameter( 'days' , new \DateTime('+'.$days.' day'));
		$queryBuilder = $queryBuilder->setParameter( 'days' , new \DateTime($days.' days ago'));
		
		
		return $queryBuilder->getQuery()->getResult();
	}
	
	
	/**
	 * getAdverts selon pagination
	 * @param : $page : string
	 * @param : $nbPerPage  : int
	 */
	public function getAdverts($page, $nbPerPage)
	{
		// Méthode 1 : en passant par l'entitymanager
		// Dans un repo, $this->_entityName est le namespace de l'entité gérée ici
		// $queryBuilder = $this->_em->createQueryBuilder()->select('a')->from($this->_entityName,'a');
		// Méthode 2 : en passant par le raccourci, recommandé 
		$queryBuilder = $this->createQueryBuilder('a');
		// Jointure sur l'attribut image
		$queryBuilder = $queryBuilder->leftJoin('a.image','img')->addSelect('img');
		// Jointure sur l'attribut categories
		$queryBuilder = $queryBuilder->leftJoin('a.categories','cat')->addSelect('cat');
		// Jointure sur l'attribut advertskills
		$queryBuilder = $queryBuilder->leftJoin('a.advertskilles','advskil')->addSelect('advskil');
		// Jointure sur l'attribut skill de l'entité advert skill, Moins de 7 requtes avec le même code dans twig
		$queryBuilder = $queryBuilder->leftJoin('advskil.skill','skill')->addSelect('skill');
		$queryBuilder->orderBy('a.date','DESC');
		// get Query à partir du QueryBuider
		$query = $queryBuilder->getQuery();
		// Pagination 
		$query
			// On définit l'annonce à partir de laquelle commencer la liste
		->setFirstResult(($page-1) * $nbPerPage)
			// Ainsi que le nombre d'annonce à afficher sur une page
		->setMaxResults($nbPerPage);
		// Pagination 
		// get Result à partir de la query
		// $results = $query->getResult();
		// Les jointures se font simplement en utilisant les attributs existants de l'entité racine Advert
		// return $results;
		return new Paginator($query, true);
	}
	
	
	public function myFindAllDQL(){
		$query = $this->_em->createQuery('SELECT a from OCPlatformBundle:Advert a');
		$results = $query->getResult();
		return $results;
	}
	
	
	public function myFindOne($id){
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.id = :id')->setParameter('id', $id);
		return $qb->getQuery()->getResult();
	}
	
	public function findByAuthorAndDate($author, $year){
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.author = :author')->setParameter('author', $author)
			->andWhere('a.date < :year')->setParameter('year', $year)
			->orderBy('a.date', 'DESC');
		return $qb->getQuery()->getResult();	
	}
	
	public function whereCurrentYear(QueryBuilder $qb){
		$qb->andWhere('a.date BETWEEN :start AND :end')
			->setParameter('start', new \Datetime(date('Y').'-01-01'))
			->setParameter('end', new \Datetime(date('Y').'-12-31'));
	}
	
	
	public function myFind(){
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.author = :author')->setParameter('author', 'Admin');
		$this->whereCurrentYear($qb);
		$qb->orderBy('a.date', 'DESC');
		return $qb->getQuery()->getResult();	
	}
	
	
	public function getAdvertWithApplications(){
		// On ne peut faire une jointure que si l'entité du From possède un attribut vers l'entité à joindre
		$qb = $this->createQueryBuilder('a')->leftJoin('a.applications','app')->addSelect('app');
		return $qb->getQuery()->getResult();
	}
	
	
	public function getAdvertWithCategories(string $categoryName){
		$qb = $this->createQueryBuilder('a');
		//$qb->innerJoin('a.categories','cat','WITH','cat.name = "'.$categoryName.'"')->addSelect('cat');
		$qb->innerJoin('a.categories','cat')->addSelect('cat');
		$qb->where('cat.name = :name')->setParameter('name' , $categoryName);
		//$qb->where($qb->expr()->in('cat.name', $categoryName));
		return $qb->getQuery()->getResult();
	}

}
